site_name: Rigging
site_description: A lightweight LLM interaction framework
site_author: Dreadnode
site_url: https://rigging.dreadnode.io
repo_url: https://github.com/dreadnode/rigging

nav:
  - Home: index.md
  - Topics:
    - Generators: topics/generators.md
    - Chats: topics/chats.md
    - Models: topics/models.md
    - Tools: topics/tools.md
    - Logging: topics/setup_logging.md
  - API:
    - rigging.chat: api/chat.md
    - rigging.completion: api/completion.md
    - rigging.generator: api/generator.md
    - rigging.model: api/model.md
    - rigging.message: api/message.md
    - rigging.tool: api/tool.md
    - rigging.parsing: api/parsing.md
    - rigging.logging: api/logging.md
    - rigging.error: api/error.md


theme:
  logo: assets/logo_black.png
  favicon: assets/logo_white.png
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: custom
  features:
    - content.code.copy
    - content.code.annotate
    - toc.integrate
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tabs

plugins:
  - search
  - section-index
  - social
  - mkdocstrings:
      handlers:
        python:
          paths: [rigging]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            heading_level: 2
            merge_init_into_class: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true

watch:
  - rigging/

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

extra:
  homepage: https://dreadnode.io
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/dreadnode
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/dreadnode
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/rigging/