site_name: Rigging
site_description: A lightweight LLM interaction framework
site_author: Dreadnode
site_url: https://rigging.dreadnode.io
repo_url: https://github.com/dreadnode/rigging

nav:
  - Introduction: index.md
  - Generators: tutorial/generators.md
  - Chats: tutorial/chat.md
  - Models: tutorial/model.md
  - Tools: tutorial/tools.md
  - Logging: tutorial/logging.md
  - API:
      - rigging.chat: api/chat.md
      - rigging.generator: api/generator.md
      - rigging.message: api/message.md
      - rigging.model: api/model.md
      - rigging.tool: api/tool.md
      - rigging.logging: api/logging.md
      - rigging.error: api/error.md

theme:
  logo: assets/logo_black.png
  favicon: assets/logo_white.png
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: custom
  features:
    - toc.integrate
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.path
    - content.code.copy
    - navigation.top

plugins:
  - search
  - section-index
  - mkdocstrings

watch:
  - rigging/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

extra:
  homepage: https://dreadnode.io